const actionTypes = Object.freeze({
  //app
  APP_START_UP_COMPLETE: "APP_START_UP_COMPLETE",
  SET_CONTENT_OF_CONFIRM_MODAL: "SET_CONTENT_OF_CONFIRM_MODAL",
  CHANGE_LANGUAGE: "CHANGE_LANGUAGE",

  //user
  ADD_USER_SUCCESS: "ADD_USER_SUCCESS",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  PROCESS_LOGOUT: "PROCESS_LOGOUT",
  USER_LOGIN_FAIL: "USER_LOGIN_FAIL",

  //admin
  FETCH_GENDER_START: "FETCH_GENDER_START",
  FETCH_GENDER_SUCCESS: "FETCH_GENDER_SUCCESS",
  FETCH_GENDER_FAIL: "FETCH_GENDER_FAIL",

  FETCH_POSITION_SUCCESS: "FETCH_POSITION_SUCCESS",
  FETCH_POSITION_FAIL: "FETCH_POSITION_FAIL",

  FETCH_ROLE_SUCCESS: "FETCH_ROLE_SUCCESS",
  FETCH_ROLE_FAIL: "FETCH_ROLE_FAIL",

  SAVE_USER_SUCCESS: "SAVE_USER_SUCCESS",
  SAVE_USER_FAIL: "SAVE_USER_FAIL",

  EDIT_USER_SUCCESS: "EDIT_USER_SUCCESS",
  EDIT_USER_FAIL: "EDIT_USER_FAIL",

  DELETE_USER_SUCCESS: "DELETE_USER_SUCCESS",
  DELETE_USER_FAIL: "DELETE_USER_FAIL",

  FETCH_ALL_USER_SUCCESS: "FETCH_ALL_USER_SUCCESS",
  FETCH_ALL_USER_FAIL: "FETCH_ALL_USER_FAIL",

  FETCH_TOP_DOCTORS_SUCCESS: "FETCH_TOP_DOCTORS_SUCCESS",
  FETCH_TOP_DOCTORS_FAIL: "FETCH_TOP_DOCTORS_FAIL",

  FETCH_ALL_DOCTORS_SUCCESS: "FETCH_ALL_DOCTORS_SUCCESS",
  FETCH_ALL_DOCTORS_FAIL: "FETCH_ALL_DOCTORS_FAIL",

  SAVE_INFO_DOCTOR_SUCCESS: "SAVE_INFO_DOCTOR_SUCCESS",
  SAVE_INFO_DOCTOR_FAIL: "SAVE_INFO_DOCTOR_FAIL",

  FETCH_TIME_ALLCODE_SUCCESS: "FETCH_TIME_ALLCODE_SUCCESS",
  FETCH_TIME_ALLCODE_FAIL: "FETCH_TIME_ALLCODE_FAIL",

  FETCH_REQUIRED_INFO_START: "FETCH_REQUIRED_INFO_START",
  FETCH_REQUIRED_INFO_SUCCESS: "FETCH_REQUIRED_INFO_SUCCESS",
  FETCH_REQUIRED_INFO_FAIL: "FETCH_REQUIRED_INFO_FAIL",
});

export default actionTypes;
